apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    admission-policy-test: abc
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: sleep
        image: alpine
        command: ["sh"]
        args: ["-c", "sleep 1"]
