apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-role-csr-subresource-star
  labels:
    admission-policy-test: abc
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/*"]
  verbs: ["update"]
